{% set version = "0.900" %}

package:
  name: mypy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mypy/mypy-{{ version }}.tar.gz
  sha256: 65c78570329c54fb40f956f7645e2359af5da9d8c54baa44f461cdc7f4984108
  patches:
    - 0001-Drop-Werror.patch

build:
  number: 0
  script:
    - export MYPY_USE_MYPYC=1  # [not win]
    - set MYPY_USE_MYPYC=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mypy = mypy.__main__:console_entry
    - stubgen = mypy.stubgen:main
    - dmypy = mypy.dmypy.client:console_entry
    - stubtest = mypy.stubtest:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - mypy_extensions >=0.4.3,<0.5.0
    - typed-ast >=1.4.0,<1.5.0  # [py<38]
    - typing_extensions >=3.7.4
    - toml
  run:
    - python
    - mypy_extensions >=0.4.3,<0.5.0
    - typed-ast >=1.4.0,<1.5.0  # [py<38]
    - typing_extensions >=3.7.4
    # extra: dmypy
    - psutil >=4.0

test:
  imports:
    - mypy
    - mypy.plugins
    - mypy.server
    - mypy.dmypy
  commands:
    - mypy --help
    - stubgen --help
    - dmypy --help
    - stubtest --help
    - dir %SP_DIR%\mypy\*.pyd /s /b  # [win]
    - ls $SP_DIR/mypy/*.so  # [linux]

about:
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Optional static typing for Python
  description: |
    Add type annotations to your Python programs, and use mypy to type check
    them. Mypy is essentially a Python linter on steroids, and it can catch
    many programming errors by analyzing your program, withoutactually having
    to run it.  Mypy has a powerful type system with features such as type
    inference, gradual typing, generics and union types.
  doc_url: http://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
