{% set name = "mypy" %}
{% set version = "0.660" %}
{% set sha256 = "986a7f97808a865405c5fd98fae5ebfa963c31520a56c783df159e9a81e41b3e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  noarch: python
  entry_points:
    - mypy=mypy.__main__:console_entry
    - stubgen=mypy.stubgen:main
    - dmypy=mypy.dmypy:console_entry
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - mypy_extensions >=0.4.0,<0.5.0
    - python >=3.4
    - typed-ast >=1.1.0,<1.2.0
    - psutil >=5.4.0,<5.5.0

test:
  imports:
    - mypy
    - mypy.plugins
    - mypy.server
    - mypy.test
  commands:
    - mypy --help
    - stubgen --help
    - dmypy --help

about:
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  # https://github.com/python/mypy/issues/4247
  # license_file: LICENSE
  summary: Optional static typing for Python
  description: |
    Add type annotations to your Python programs, and use mypy to type check
    them. Mypy is essentially a Python linter on steroids, and it can catch
    many programming errors by analyzing your program, withoutactually having
    to run it.  Mypy has a powerful type system with features such as type
    inference, gradual typing, generics and union types.
  doc_url: http://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy

extra:
  recipe-maintainers:
    - nehaljwani
