{% set version = "0.990" %}

package:
  name: mypy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mypy/mypy-{{ version }}.tar.gz
  sha256: 72382cb609142dba3f04140d016c94b4092bc7b4d98ca718740dc989e5271b8d

build:
  number: 1
  script:
    - export MYPY_USE_MYPYC=1  # [not win]
    - export SETUPTOOLS_USE_DISTUTILS=stdlib  # [not win]
    - set MYPY_USE_MYPYC=1     # [win]
    - set SETUPTOOLS_USE_DISTUTILS=stdlib  # [win]
    # mypy searches for <>-stubs in site.getsitepackages()
    # which points to $SP_DIR, even in cross-python
    - cp -rv $BUILD_PREFIX/lib/python$PY_VER/site-packages/*-stubs $SP_DIR  # [build_platform != target_platform]
    - cp -rv $BUILD_PREFIX/lib/python$PY_VER/site-packages/tomli* $SP_DIR  # [build_platform != target_platform]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mypy = mypy.__main__:console_entry
    - stubgen = mypy.stubgen:main
    - dmypy = mypy.dmypy.client:console_entry
    - stubtest = mypy.stubtest:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    # mypy's build imports this module, which has a C extension,
    # so it has to be native to the build platform
    - typed-ast >=1.4.0,<2                   # [build_platform != target_platform and py<38]
    - tomli >=1.1.0
  host:
    - python
    - pip
    - mypy_extensions >=0.4.3
    - typed-ast >=1.4.0,<2  # [py<38]
    - typing_extensions >=3.10
    - types-setuptools
    - types-psutil
    - types-typed-ast >=1.5.8,<1.6.0
    - tomli >=1.1.0
  run:
    - python
    - mypy_extensions >=0.4.3
    - typed-ast >=1.4.0,<2  # [py<38]
    - typing_extensions >=3.10
    - tomli >=1.1.0
    # extra: dmypy
    - psutil >=4.0

test:
  imports:
    - mypy
    - mypy.plugins
    - mypy.server
    - mypy.dmypy
  commands:
    - mypy --help
    - stubgen --help
    - dmypy --help
    - stubtest --help
    - dir %SP_DIR%\mypy\*.pyd /s /b  # [win]
    - ls $SP_DIR/mypy/*.so  # [linux and not (aarch64 and py==310)]

about:
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Optional static typing for Python
  description: |
    Add type annotations to your Python programs, and use mypy to type check
    them. Mypy is essentially a Python linter on steroids, and it can catch
    many programming errors by analyzing your program, without actually having
    to run it.  Mypy has a powerful type system with features such as type
    inference, gradual typing, generics and union types.
  doc_url: http://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - matthiasdiener
